name       : duperemove
version    : 0.11.2
release    : 1
source     :
    - https://github.com/markfasheh/duperemove/archive/v0.11.2.tar.gz : e162c2cf99c9d1e1e111cf84fa2615490a7d654173a3719651a962257bf8179e
license    : GPL-2.0-only
component  : system.utils
summary    : Tools for deduping file systems
description: |
    Duperemove is a simple tool for finding duplicated extents and submitting them for deduplication. When given a list of files it will hash their contents on a block by block basis and compare those hashes to each other, finding and categorizing blocks that match each other. When given the -d option, duperemove will submit those extents for deduplication using the Linux kernel extent-same ioctl.
builddeps  :
    - pkgconfig(sqlite3)
build      : |
    %make
install    : |
    %make_install PREFIX=/usr
