name       : duperemove
version    : '0.12'
release    : 4
source     :
    - https://github.com/markfasheh/duperemove/archive/refs/tags/v0.12.tar.gz : 53c0e1526d8bdb16ff18ad8a417570c829f8a11dea27060061c73dd6387326f4
license    : GPL-2.0-only
component  : system.utils
summary    : Tools for deduping file systems
description: |
    Duperemove is a simple tool for finding duplicated extents and submitting them for deduplication. When given a list of files it will hash their contents on a block by block basis and compare those hashes to each other, finding and categorizing blocks that match each other. When given the -d option, duperemove will submit those extents for deduplication using the Linux kernel extent-same ioctl.
builddeps  :
    - pkgconfig(sqlite3)
build      : |
    %make
install    : |
    %make_install PREFIX=/usr
