name       : duperemove
version    : 0.11.3
release    : 3
source     :
    - https://github.com/markfasheh/duperemove/archive/refs/tags/v0.11.3.tar.gz : 4161e6a7e9b53bb2c190e48eba0aa3028aca27874751aec351550dbae4964da0
license    : GPL-2.0-only
component  : system.utils
summary    : Tools for deduping file systems
description: |
    Duperemove is a simple tool for finding duplicated extents and submitting them for deduplication. When given a list of files it will hash their contents on a block by block basis and compare those hashes to each other, finding and categorizing blocks that match each other. When given the -d option, duperemove will submit those extents for deduplication using the Linux kernel extent-same ioctl.
builddeps  :
    - pkgconfig(sqlite3)
build      : |
    %make
install    : |
    %make_install PREFIX=/usr
